version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: platzi
      POSTGRES_PASSWORD: platzi
      POSTGRES_DB: platziverse
    volumes:
      - ./platziverse-db/postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
